### ISSUE TITLE
Consider using python:2.7-alpine as base image

### ISSUE THREAD

**Issue by avoinea** [plone/plone.docker#8]
As `python:2.7-slim` is twice bigger than `python:2.7-alpine` I think we should consider using `alpine` base image instead of `debian`

**Comment by demarant** [comment]
+1
we could even go that far and start the dockerfile with: 
`FROM scratch`
if possible, basically creating a "portable tiny microcontainer":http://www.iron.io/blog/2016/01/microcontainers-tiny-portable-containers.html containing only the exact code needed to run plone, nothing more.
otherwise alpine is a very good candidate.

**Comment by avoinea** [comment]
Now we also have images with tag `-alpine`
