### ISSUE TITLE
Docker images for testing on Gitlab-CI?

### ISSUE THREAD

**Issue by MrTango** [plone/plone.docker#95]
I tried using the images for testing on Gitlab-CI but failed because there is no bash in the docker images. Can we fix this or provide other images siutable for testing?

**Comment by svx** [comment]
Well, that is not surprising because we try do only use the bare minimal requirements and bash is not one of them.

You can 'easily' fix that yourself by building your own image based on the ``plone.docker`` one.

We simply can not cover every use case, your requirements may be different from the next persons one who needs zsh or something else.
If we would start to include all of this into the image, it would be a really bad idea.

Building your own images is not hard and not that much work and you will get exactly all requirements you need :)

**Comment by avoinea** [comment]
@MrTango There is bash inside, what's your error?!

```
docker run -it --rm plone:5 bash
```
